### ISSUE TITLE
Implement Video page back-end server

### ISSUE THREAD

**Issue by AbhayChandel** [AbhayChandel/drool-java-server#50]
- [x] Create Database structure along with views.

- [x] Retrieve Video card and Video page views.

- [x] https://github.com/AbhayChandel/drool-java-server/issues/52 (Persist video like to database)

- [x] https://github.com/AbhayChandel/drool-java-server/issues/53 (Persist & Delete video comment to databse)

- [ ] https://github.com/AbhayChandel/drool-java-server/issues/72 (Save video comment edits)

- [x] https://github.com/AbhayChandel/drool-java-server/issues/54 (Persist like on video comment to database)

- [x] https://github.com/AbhayChandel/drool-java-server/issues/55 (Persist new video to database)

- [x] #74 (Persist video post edits.)

**Comment by AbhayChandel** [comment]
Point 1 and 2, implemented with PR #51

**Comment by AbhayChandel** [comment]
Issue #55, implemented with PR https://github.com/AbhayChandel/drool-java-server/pull/66

**Comment by AbhayChandel** [comment]
Issue #52, implemented with PR #69

**Comment by AbhayChandel** [comment]
Issue #54, implemented with PR #75

**Comment by AbhayChandel** [comment]
This issue is for PostgreSQL. We have moved to MongoDB.
